### ISSUE TITLE
Is this really the right LDN inbox?

### ISSUE THREAD

**Issue by gobengo** [linkedresearch/linkedresearch.org#4]
Ok, #3 was totally my fault. But I fixed that and *think* I have a real issue now. Man, it would really be embarassing if I've misdiagnosed this one too.

I'm performing LDN inbox discovery for https://linkedresearch.org/ldn/tests/

I think it's pointing me to https://linkedresearch.org/ldn/tests//ldn/tests/inbox/, which 404s

I think you may want it to point to https://linkedresearch.org/ldn/tests/inbox , which does not 404, and is what @csarven told me to use in a PM a month or so ago.

```
ben@bengo-air ~ $ curl "https://linkedresearch.org/ldn/tests/" -s -D - -o /dev/null
HTTP/1.1 200 OK
Date: Fri, 30 Dec 2016 12:32:15 GMT
Server: Apache/2.4.18 (Ubuntu)
X-Powered-By: https://github.com/csarven/mayktso
...
Link: <https://linkedresearch.org/ldn/tests//ldn/tests/inbox/>; rel="http://www.w3.org/ns/ldp#inbox", <http://www.w3.org/ns/ldp#Resource>; rel="type", <http://www.w3.org/ns/ldp#RDFSource>; rel="type"
...
```

**Comment by rhiaro** [comment]
Yeah that does look wrong. The code is being worked on and in flux right now though; we had some issues with relative vs absolute paths. Stand by.

**Comment by csarven** [comment]
Thanks for raising this. Looks like I mangled some stuff and didn't review (some of that was written awhile ago).

This repository is for the linkedresearch.org website. For LDN issues, please use the repository here: https://github.com/csarven/ldn-tests/
