### ISSUE TITLE
LinkedDataNotifications to enable referencing of self-published articles

### ISSUE THREAD

**Issue by jibe-b** [linkedresearch/linkedresearch.org#5]
I am trying to see how LinkedData Notifications could be used within a process of content referencing and aggregation.

Let's consider an author (a scientist) who publishes a document online (scientific publication).
She does it using dokie.li and sends a LinkedData Notification to the Inbox of a content referencement and agregation website.

Then this website may use the metadata of the publication in any standard way, such as exposing it through a OAI-PMH or better ResourceSync. Text-mining applications may then use such a referencing/agregator website (for example Core) as en entry for getting papers to mine (see OpenMinTeD for example).

I do realize that this proxy website "recentralizes", somehow. But when it helps grasping loads of contents, let's say it helps.

**Comment by jibe-b** [comment]
May I ask for opinions about this?

This may already have been discussed and then I'd join the discussion where it be!

**Comment by csarven** [comment]
I think https://linkedresearch.org/cloud 's LDN Inbox may be addressing this issue. It is not constrained to "self-published" articles. Check it out. If that's covered with LORC, we can close this issue.

**Comment by jibe-b** [comment]
It does! (sorry for the late reply)
